# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=3000']
      # - id: check-json
      - id: check-toml
      - id: check-yaml
<<<<<<< HEAD
      --allow-missing-config
  #     - id: end-of-file-fixer
  #     - id: trailing-whitespace
=======
      - id: end-of-file-fixer
        exclude: ^tests/resources/
      # - id: trailing-whitespace

>>>>>>> 0c8befcd023faecc60940ae18f96ae82f53bdf01
  # - repo: https://github.com/astral-sh/ruff-pre-commit
  #   rev: v0.6.9
  #   hooks:
  #     - id: ruff
  #       args: [--fix, --exit-non-zero-on-fix, --show-fixes]
  #     - id: ruff-format

  # - repo: local
  #   hooks:
  #     - id: pytest
  #       name: pytest
  #       entry: pytest
  #       language: system
  #       types: [python]
  #       pass_filenames: false
